site_name: edgfe-vox
site_description: C++ client for edge server voice interactions
repo_url: https://github.com/yourusername/edge-vox
repo_name: edge-vox

# extra_css:
#   - assets/stylesheets/logo.css
theme:
  name: material
  # custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
      scheme: default
      primary: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  font:
    text: Avenir Next Condensed
    code: Avenir Next Condensed
  # favicon: assets/favicon.png
  # logo: assets/logo.png

plugins:
  - search
  - git-revision-date
  - git-authors
  - minify:
      minify_html: true
  - mkdoxy:
      projects:
        edge-vox:
          src: include
          full_doc: true
          recursive: true
          generate_index: true
          doxy_filename: Doxyfile

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  
nav:
  - Home: index.md
  - Getting Started:
    - usage/overview.md
  #   - Build Environment:
  #     - usage/build_environment/usage_with_windows.md
  #     - usage/build_environment/usage_with_mac.md
  #     - usage/build_environment/usage_with_linux.md
    - API Documentation:
    - Examples:
      - usage/demo.md
  #     - usage/lowwi_demo_mic.md
  # - Implementation:
  #   - about/implementation.md
  - Contributing:
    - contributing/rules.md
    - contributing/license.md